import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], BUCKET='student-documents', MAX=10*1024*1024;
const ADMIN_EMAIL='katthepremkumar@gmail.com';
let db,user,profile={},docs=[],adminUsers=[];
function msg(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bytes(n){return n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
function renderList(arr,sel){$(sel).innerHTML=arr.map(d=>'<article class="doc"><div class="fileicon">'+esc((d.original_name.split('.').pop()||'FILE').toUpperCase().slice(0,4))+'</div><div class="docinfo"><strong>'+esc(d.original_name)+'</strong><small>'+esc(d.category)+' · '+bytes(d.size_bytes)+' · '+new Date(d.created_at).toLocaleDateString()+'</small></div><span class="tag">'+esc(d.category)+'</span><div class="actions"><button data-down="'+esc(d.id)+'">↓</button><button data-del="'+esc(d.id)+'">×</button></div></article>').join('')}
function render(){docs.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('#count').textContent=docs.length;$('#total').textContent=docs.length;$('#cats').textContent=new Set(docs.map(d=>d.category)).size;renderList(docs.slice(0,4),'#recent');filterDocs();$('#emptyRecent').classList.toggle('hidden',docs.length>0)}
function filterDocs(){let q=$('#search').value.toLowerCase(),c=$('#filter').value,arr=docs.filter(d=>d.original_name.toLowerCase().includes(q)&&(c==='All categories'||c===d.category));renderList(arr,'#allDocs');$('#emptyDocs').classList.toggle('hidden',arr.length>0);$('#allDocs').classList.toggle('hidden',arr.length===0)}
function setProfile(){let n=profile.full_name||user.user_metadata?.full_name||user.email.split('@')[0];$('#welcome').textContent=n;$('#user').textContent=n+' · '+user.email;$('#fullName').value=profile.full_name||n;$('#studentId').value=profile.student_id||'';$('#college').value=profile.college||'';$('#course').value=profile.course||''}
async function load(){let p=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();if(p.error)throw p.error;profile=p.data||{};if(!profile.id){let ins=await db.from('profiles').insert({id:user.id,email:user.email||'',full_name:user.user_metadata?.full_name||user.email?.split('@')[0]||'Student'});if(ins.error)throw ins.error;let again=await db.from('profiles').select('*').eq('id',user.id).single();if(again.error)throw again.error;profile=again.data}else if(profile.email!==user.email){let upd=await db.from('profiles').update({email:user.email||''}).eq('id',user.id);if(upd.error)throw upd.error;profile.email=user.email||''}setProfile();let r=await db.from('documents').select('id,original_name,storage_path,category,mime_type,size_bytes,created_at').order('created_at',{ascending:false});if(r.error)throw r.error;docs=r.data||[];render()}
async function loadAdmin(){if((user.email||'').toLowerCase()!==ADMIN_EMAIL)return;$('#adminNav').classList.remove('hidden');let p=await db.from('profiles').select('id,email,full_name,created_at').order('created_at',{ascending:false});if(p.error)throw p.error;let a=await db.from('login_activity').select('user_id,email,logged_in_at').order('logged_in_at',{ascending:false});if(a.error)throw a.error;const latest=new Map();for(const row of a.data||[])if(!latest.has(row.user_id))latest.set(row.user_id,row.logged_in_at);adminUsers=(p.data||[]).map(x=>({...x,last_login:latest.get(x.id)||'Not recorded'}));renderAdmin()}
function renderAdmin(){const q=$('#adminSearch').value.toLowerCase();const rows=adminUsers.filter(x=>(x.email||'').toLowerCase().includes(q)||(x.full_name||'').toLowerCase().includes(q));$('#adminTotal').textContent=adminUsers.length;$('#adminRows').innerHTML=rows.map(x=>'<article class="doc"><div class="fileicon">USR</div><div class="docinfo"><strong>'+esc(x.email||'No email')+'</strong><small>'+esc(x.full_name||'Student')+' · Joined '+new Date(x.created_at).toLocaleDateString()+'</small></div><span class="tag">'+esc(x.last_login==='Not recorded'?x.last_login:new Date(x.last_login).toLocaleString())+'</span></article>').join('');$('#adminEmpty').classList.toggle('hidden',rows.length>0)}
function view(v){['home','docs','profile','admin'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==v));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#crumb').textContent={home:'Overview',docs:'My documents',profile:'Student profile',admin:'Admin dashboard'}[v];if(v==='docs')filterDocs();if(v==='admin')renderAdmin()}
async function login(){let r=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href.split('#')[0].split('?')[0]}});if(r.error)$('#authError').textContent=r.error.message}
async function start(u){user=u;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');try{await load();if((user.email||'').toLowerCase()===ADMIN_EMAIL){$('#adminNav').classList.remove('hidden');}const activity=await db.from('login_activity').insert({user_id:user.id,email:user.email||''});if(activity.error)console.warn('Login activity was not recorded:',activity.error.message);if((user.email||'').toLowerCase()===ADMIN_EMAIL)await loadAdmin()}catch(e){console.error(e);msg('Backend setup error. Run the latest supabase-schema.sql in Supabase SQL Editor.')}}
async function upload(e){e.preventDefault();let f=$('#file').files[0];if(!f)return;if(f.size<1||f.size>MAX){$('#uploadError').textContent='Choose a file up to 10 MB.';return}let allowed=['application/pdf','image/png','image/jpeg','image/webp','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/plain'];if(!allowed.includes(f.type)){$('#uploadError').textContent='Unsupported file type.';return}let btn=e.submitter;btn.disabled=true;btn.textContent='Uploading…';let clean=f.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-120)||'document',path=user.id+'/'+crypto.randomUUID()+'-'+clean;try{let up=await db.storage.from(BUCKET).upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;let ins=await db.from('documents').insert({user_id:user.id,original_name:f.name,storage_path:path,category:$('#category').value,mime_type:f.type,size_bytes:f.size});if(ins.error){await db.storage.from(BUCKET).remove([path]);throw ins.error}$('#modal').classList.add('hidden');$('#uploadForm').reset();await load();msg('Document uploaded securely.')}catch(err){$('#uploadError').textContent=err.message||'Upload failed.'}finally{btn.disabled=false;btn.textContent='Upload securely'}}
async function download(id){let d=docs.find(x=>x.id===id);if(!d)return;let r=await db.storage.from(BUCKET).download(d.storage_path);if(r.error){msg(r.error.message);return}let url=URL.createObjectURL(r.data),a=document.createElement('a');a.href=url;a.download=d.original_name;a.click();URL.revokeObjectURL(url)}
async function del(id){let d=docs.find(x=>x.id===id);if(!d||!confirm('Delete '+d.original_name+' permanently?'))return;let r=await db.storage.from(BUCKET).remove([d.storage_path]);if(r.error){msg(r.error.message);return}let m=await db.from('documents').delete().eq('id',id);if(m.error){msg(m.error.message);return}await load();msg('Document deleted.')}
async function save(e){e.preventDefault();let payload={id:user.id,full_name:$('#fullName').value.trim(),student_id:$('#studentId').value.trim()||null,college:$('#college').value.trim()||null,course:$('#course').value.trim()||null,updated_at:new Date().toISOString()};let r=await db.from('profiles').upsert(payload);if(r.error){$('#profileMsg').textContent=r.error.message;return}profile=payload;setProfile();$('#profileMsg').textContent='Saved.'}
$$('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));['upload1','upload2','upload3'].forEach(id=>$('#'+id).onclick=()=>{$('#modal').classList.remove('hidden');$('#uploadError').textContent=''});$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};$('#uploadForm').onsubmit=upload;$('#search').oninput=filterDocs;$('#filter').onchange=filterDocs;$('#profileForm').onsubmit=save;$('#adminSearch').oninput=renderAdmin;
document.addEventListener('click',e=>{let d=e.target.closest('[data-down]'),x=e.target.closest('[data-del]');if(d)download(d.dataset.down);if(x)del(x.dataset.del)});
if(!SUPABASE_URL.startsWith('https://')||SUPABASE_ANON_KEY.includes('PASTE_')){$('#authError').textContent='Setup needed: add your Supabase URL and public key in config.js.';$('#login').disabled=true}else{db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);$('#login').onclick=login;db.auth.onAuthStateChange((event,session)=>{if(session?.user)queueMicrotask(()=>start(session.user));else if(event==='SIGNED_OUT')location.reload()});db.auth.getSession().then(({data,error})=>{if(error)$('#authError').textContent=error.message;else if(data.session?.user)start(data.session.user)});$('#logout').onclick=async()=>{await db.auth.signOut()}}
