-- Run this whole script in Supabase SQL Editor. Safe to re-run.
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '' check(char_length(full_name)<=70),student_id text check(student_id is null or char_length(student_id)<=40),college text check(college is null or char_length(college)<=100),course text check(course is null or char_length(course)<=80),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.profiles add column if not exists email text;
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,original_name text not null check(char_length(original_name) between 1 and 255),storage_path text not null unique,category text not null default 'Other' check(category in ('Identity','Academics','Certificates','Projects','Other')),mime_type text not null,size_bytes bigint not null check(size_bytes>0 and size_bytes<=10485760),created_at timestamptz not null default now(),constraint path_matches_owner check(split_part(storage_path,'/',1)=user_id::text));
create index if not exists documents_user_created_idx on public.documents(user_id,created_at desc);
create table if not exists public.login_activity(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,email text not null,logged_in_at timestamptz not null default now());
create index if not exists login_activity_user_time_idx on public.login_activity(user_id,logged_in_at desc);
alter table public.profiles enable row level security;
alter table public.documents enable row level security;
alter table public.login_activity enable row level security;
drop policy if exists "Profiles select own" on public.profiles;
create policy "Profiles select own" on public.profiles for select to authenticated using((select auth.uid())=id);
drop policy if exists "Profiles admin select" on public.profiles;
create policy "Profiles admin select" on public.profiles for select to authenticated using((select auth.jwt()->>'email')='katthepremkumar@gmail.com');
drop policy if exists "Profiles insert own" on public.profiles;
create policy "Profiles insert own" on public.profiles for insert to authenticated with check((select auth.uid())=id and email=(select auth.jwt()->>'email'));
drop policy if exists "Profiles update own" on public.profiles;
create policy "Profiles update own" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id and email=(select auth.jwt()->>'email'));
drop policy if exists "Documents select own" on public.documents;
create policy "Documents select own" on public.documents for select to authenticated using((select auth.uid())=user_id);
drop policy if exists "Documents insert own" on public.documents;
create policy "Documents insert own" on public.documents for insert to authenticated with check((select auth.uid())=user_id and split_part(storage_path,'/',1)=(select auth.uid())::text);
drop policy if exists "Documents delete own" on public.documents;
create policy "Documents delete own" on public.documents for delete to authenticated using((select auth.uid())=user_id);
drop policy if exists "Login activity insert own" on public.login_activity;
create policy "Login activity insert own" on public.login_activity for insert to authenticated with check(user_id=(select auth.uid()) and email=(select auth.jwt()->>'email'));
drop policy if exists "Login activity admin read" on public.login_activity;
create policy "Login activity admin read" on public.login_activity for select to authenticated using((select auth.jwt()->>'email')='katthepremkumar@gmail.com');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('student-documents','student-documents',false,10485760,array['application/pdf','image/png','image/jpeg','image/webp','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/plain']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Locker files select own folder" on storage.objects;
create policy "Locker files select own folder" on storage.objects for select to authenticated using(bucket_id='student-documents' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Locker files insert own folder" on storage.objects;
create policy "Locker files insert own folder" on storage.objects for insert to authenticated with check(bucket_id='student-documents' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Locker files delete own folder" on storage.objects;
create policy "Locker files delete own folder" on storage.objects for delete to authenticated using(bucket_id='student-documents' and (storage.foldername(name))[1]=(select auth.uid())::text);
